cache: bundler
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-19mode
  - jruby-9.0.0.0
  - jruby-head
  - ruby-head
script: bundle exec rspec
sudo: false

before_install: gem install bundler -v 1.10.6
bundler_args: --without development

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true

addons:
  code_climate:
    repo_token: bcca45c494e41a9b9a45faf22ebace905de2559cd5480743c145d01b49a479a8
